### ISSUE TITLE
Get backdrop drush extension installed on Platform.sh

### ISSUE THREAD

**Issue by serundeputy** [platformsh/platformsh-example-backdrop#1]
* install backdrop drush extension (in `build` step?)
* add build steps to import config on deploys:
  * `drush bcim -y`
  * `drush cc all`

**Comment by Crell** [comment]
Drush extension now installed via build hook.  Needs testing from @serundeputy.

**Comment by serundeputy** [comment]
Great! @Crell how can I test?  Can you add me as a developer to this project https://test-t6dnbai-glk6khcjm3teq.us.platform.sh/ and I'll configure config workflow and `build` step to deploy config via drush and check that it works?

**Comment by serundeputy** [comment]
PR: https://github.com/platformsh/platformsh-example-backdrop/pull/2

Adds `deploy` hook to import backdrop config on deploy: `drush bcim -y`.
