### ISSUE TITLE
Update to Backdrop 1.8.0.

### ISSUE THREAD

**Issue by serundeputy** [platformsh/platformsh-example-backdrop#3]
Update to Backdrop 1.8.0.

**Comment by serundeputy** [comment]
PR: https://github.com/platformsh/platformsh-example-backdrop/pull/4

@Crell Let me know if you want me to assign you as reviewer of these PRs or if you'd just like me to maintain and merge upgrades.

**Comment by Crell** [comment]
If it's just routine Backdrop maintenance (as the two PRs that are outstanding now appear to be), no need to loop me in.  Feel free to tag me if you specifically want my input on something, though.
